"""add media model

Revision ID: dcc632a8e689
Revises: bbf1ede499dc
Create Date: 2025-07-30 06:44:14.656678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc632a8e689'
down_revision: Union[str, Sequence[str], None] = 'bbf1ede499dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('url', sa.String(), nullable=False))
    op.add_column('media', sa.Column('public_id', sa.String(), nullable=False))
    op.add_column('media', sa.Column('media_type', sa.String(), nullable=False))
    op.add_column('media', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.drop_column('media', 'file_type')
    op.drop_column('media', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('media', sa.Column('file_type', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('media', 'uploaded_at')
    op.drop_column('media', 'media_type')
    op.drop_column('media', 'public_id')
    op.drop_column('media', 'url')
    # ### end Alembic commands ###
